export const documentationCopy = {
  name: 'Solidgate',
  subtitle: 'Boilerplate dokumentacija',
  overview: 'Pradžia',
  search: 'Ieškoti dokumentacijoje…',
  searchLabel: 'Ieškoti dokumentuose ir skyriuose',
  searchEmpty: 'Pagal šią užklausą nieko neradome. Pabandyk lentelės ar srauto pavadinimą.',
  searchHint: 'Dokumentai ir jų skyriai',
  current: 'Aktualu',
  historical: 'Ankstesnė būsena',
  updated: 'Atnaujinta',
  date: '2026-09-15',
  onThisPage: 'Šiame puslapyje',
  navigation: 'Dokumentacijos skyriai',
  heroEyebrow: 'SISTEMA · DUOMENYS · PATIKIMUMAS',
  heroTitle: 'Mokėjimų sistema,\nnuo pradžios iki pratęsimo.',
  heroDescription: 'Checkout, užsakymai, prenumeratos ir pinigų istorija. Visa boilerplate dokumentacija su schemomis, lentelėmis ir patikros rezultatais.',
  featuredLabel: 'PRADĖK ČIA',
  featuredTitle: 'Kas pasikeitė po pilno audito',
  featuredDescription: '2026-09-14 pataisos: saugus prisijungimas, finansinių įvykių žurnalas, renewals ir patikimos ataskaitos.',
  featuredAction: 'Skaityti pataisas',
  lifecycleTitle: 'Kaip susijungia mokėjimo dalys',
  lifecycleDescription: 'Atsakomybių žemėlapis pagal naujausias vietines pataisas. Konkrečių srautų detalės pateiktos dokumentuose.',
  sectionsTitle: 'Naršyk pagal temą',
  sectionsDescription: 'Nuo bendro vaizdo iki konkrečios DB funkcijos.',
  historyTitle: 'Dokumentų būklė aiškiai pažymėta',
  historyDescription: 'Naujausias pataisų ir diegimo aprašymas yra aktualus. Ankstesnės apžvalgos išsaugotos kaip audito kontekstas; jų elgseną lygink su pataisų dokumentu.',
  historicalNotice: 'Šis dokumentas aprašo ankstesnę sistemos būseną arba audito kontekstą. Naujausi elgsenos pakeitimai ir jų patikra aprašyti 2026-09-14 pataisose.',
  historicalAction: 'Atverti naujausias pataisas',
  sourceLabel: 'Dokumento šaltinis',
  readingLabel: 'Skaityti dokumentą',
  footer: 'Dokumentacija aprašo boilerplate kodą. Produkcinės aplinkos diegimas ir istorinių duomenų sutikrinimas yra atskiri darbai.',
  lifecycle: [
    { number: '01', title: 'Checkout', description: 'Serverio kaina ir vienas pirkimo bandymas.', table: 'orders', slug: 'payment-flows', icon: 'checkout' },
    { number: '02', title: 'Patvirtinimas', description: 'Provider statusas, patikrintas webhook ir pakartojimų kontrolė.', table: 'solidgate_webhook_events', slug: 'webhook-queues', icon: 'verify' },
    { number: '03', title: 'Pinigų istorija', description: 'Capture, refund ir chargeback — su sumomis bei datomis.', table: 'solidgate_financial_movements', slug: 'audit-fixes', icon: 'ledger' },
    { number: '04', title: 'Prieiga ir pratęsimas', description: 'Apmokėti periodai, trial datos ir subscription istorija.', table: 'entitlements · renewal_events', slug: 'renewals-invoices', icon: 'renewal' },
  ],
} as const;
